sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLED_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_xxxxxxxxxxx_key -iv $encrypted_xxxxxxxxxxx_key -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project xxxxxx-xxxxx-999999
  - gcloud config set compute/zone asia-northeast1
  - gcloud container clusters get-credentials web-k8s-template-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t ymdarake/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ymdarake/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
